name: Deploy Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - name: Deploy
        id: deploy
        uses: actions/deploy-pages@v4